kind: pipeline
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - for file in $(find ./root -type f); do shellcheck $file; done;

- name: lidarr
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/lidarr
    auto_tag: true
